ALTER TABLE trade_transactions ADD COLUMN source VARCHAR(255) NOT NULL DEFAULT 'MANUAL';
ALTER TABLE trade_transactions ALTER COLUMN source DROP DEFAULT;

CREATE TABLE portfolio_broker_holding_imports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    snapshot_item_id BIGINT NOT NULL,
    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    quantity NUMERIC(19, 6) NOT NULL,
    average_purchase_price NUMERIC(19, 4) NOT NULL,
    snapshot_synced_at TIMESTAMP(6) NOT NULL,
    -- 취소로 trade_transactions 행이 삭제된 뒤에도 생성 당시 거래 ID를 감사 목적으로
    -- 보존해야 하므로 의도적으로 외래키 제약을 걸지 않는다.
    trade_transaction_id BIGINT NOT NULL,
    approved_by_member_id BIGINT NOT NULL,
    approved_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_broker_holding_imports_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    CONSTRAINT fk_broker_holding_imports_snapshot_item
        FOREIGN KEY (snapshot_item_id) REFERENCES broker_holding_snapshot_items (id),
    CONSTRAINT fk_broker_holding_imports_approved_by_member
        FOREIGN KEY (approved_by_member_id) REFERENCES members (id),
    -- 동일 스냅샷 항목의 중복 승인을 DB 수준에서 막는다.
    CONSTRAINT uk_broker_holding_imports_snapshot_item UNIQUE (snapshot_item_id)
);

-- 감사 이력 조회는 포트폴리오별로 승인 시각 내림차순으로 읽는다.
CREATE INDEX idx_broker_holding_imports_portfolio_approved_at
    ON portfolio_broker_holding_imports (portfolio_id, approved_at DESC);
