-- 증권사 주문 이력 가져오기(읽기 전용 스테이징) 스키마다.
--
-- 이 마이그레이션은 trade_transactions를 한 컬럼도 바꾸지 않는다. 여기 만들어지는 테이블은
-- "증권사가 이렇게 보고했다"는 사실만 보존하며, 매매 원장 반영은 별도 단계(P3)에서 다룬다.
-- 그래서 실행 행과 항목 행에는 승인·취소 컬럼이 없고, 반영 사실은 링크 테이블 하나에만 남는다.

-- 실행 감사. 한 번의 "미리보기 생성" 요청이 한 행이다.
CREATE TABLE broker_order_import_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    broker_connection_id BIGINT NOT NULL,
    -- 계좌 행은 재검증에서 삭제되지 않고 DETACHED로만 표시되므로 외래키를 걸어도 안전하다.
    broker_account_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,

    -- 사용자가 요청한 구간과, 경계일 체결을 놓치지 않으려고 실제로 넓혀 조회한 구간을 함께 남긴다.
    -- 증권사는 체결일이 아니라 주문일 기준으로 조회하므로 컬럼 이름에 ordered를 남긴다.
    requested_ordered_from DATE NOT NULL,
    requested_ordered_to DATE NOT NULL,
    queried_ordered_from DATE NOT NULL,
    queried_ordered_to DATE NOT NULL,

    started_at TIMESTAMP(6) NOT NULL,
    finished_at TIMESTAMP(6),
    status VARCHAR(20) NOT NULL,

    -- 사유별 건수. 아래 배타 건수의 합은 fetched_count와 같아야 한다.
    -- 조용한 누락을 막는 것이 이 컬럼들의 존재 이유다.
    fetched_count INTEGER NOT NULL,
    staged_count INTEGER NOT NULL,
    not_filled_count INTEGER NOT NULL,
    pending_settlement_count INTEGER NOT NULL,
    control_record_count INTEGER NOT NULL,
    missing_execution_time_count INTEGER NOT NULL,
    missing_average_price_count INTEGER NOT NULL,
    unknown_status_count INTEGER NOT NULL,
    unsupported_market_count INTEGER NOT NULL,
    unsupported_currency_count INTEGER NOT NULL,
    already_imported_count INTEGER NOT NULL,
    manual_overlap_suspected_count INTEGER NOT NULL,
    duplicate_suspected_count INTEGER NOT NULL,

    -- 신호 건수. 배타 분류가 아니므로 위 합계에 들어가지 않는다.
    unknown_enum_count INTEGER NOT NULL,
    -- 커서 순회 중 같은 주문이 두 번 이상 돌아온 횟수. 중복은 합치되 사실은 남긴다.
    duplicate_fetch_count INTEGER NOT NULL,
    amount_mismatch_count INTEGER NOT NULL,
    fee_unknown_count INTEGER NOT NULL,
    buy_tax_count INTEGER NOT NULL,
    open_order_count INTEGER NOT NULL,

    reconciliation_status VARCHAR(20) NOT NULL,
    -- 대조에 사용한 보유 종목 스냅샷 시각. 스냅샷이 없으면 비어 있다.
    reconciliation_snapshot_synced_at TIMESTAMP(6),

    -- 증권사 원문 오류 메시지는 저장하지 않는다. 정제된 코드만 남긴다.
    failure_code VARCHAR(50),
    -- 비밀값도 개인정보도 아닌 불투명한 요청 상관 id다. 실패 조사에 쓸 유일한 근거라 남긴다.
    provider_request_id VARCHAR(255),

    executed_by_member_id BIGINT NOT NULL,

    CONSTRAINT fk_broker_order_import_runs_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    CONSTRAINT fk_broker_order_import_runs_connection
        FOREIGN KEY (broker_connection_id) REFERENCES broker_connections (id),
    CONSTRAINT fk_broker_order_import_runs_account
        FOREIGN KEY (broker_account_id) REFERENCES broker_accounts (id),
    CONSTRAINT fk_broker_order_import_runs_executed_by_member
        FOREIGN KEY (executed_by_member_id) REFERENCES members (id)
);

-- 목록 조회는 포트폴리오별로 시작 시각 내림차순으로 읽는다.
CREATE INDEX idx_broker_order_import_runs_portfolio_started_at
    ON broker_order_import_runs (portfolio_id, started_at DESC);

-- 실행 시점의 주문 스냅샷이다. 한 번 쓰면 바꾸지 않는다.
-- 재조회에서 값이 달라져도 기존 행을 갱신하지 않고 새 실행의 새 행으로 남겨, 무엇이 어떻게
-- 달라졌는지 두 실행을 나란히 놓고 볼 수 있게 한다.
CREATE TABLE broker_order_import_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    external_order_id VARCHAR(255) NOT NULL,
    -- 주문 식별자가 재조회마다 바뀌는지 감지하기 위한 교차 검증 값이다. 대체 키가 아니다.
    content_fingerprint VARCHAR(64) NOT NULL,

    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    -- 주문 응답에는 종목명이 없어 자산 카탈로그에서 채운다. 없으면 종목 코드를 그대로 쓴다.
    display_name VARCHAR(255) NOT NULL,

    order_side VARCHAR(10) NOT NULL,
    -- 제공자 원문 값을 감사 목적으로 보존한다. 판단은 lifecycle 컬럼으로 한다.
    provider_status_code VARCHAR(50) NOT NULL,
    provider_order_type VARCHAR(50),
    provider_time_in_force VARCHAR(50),
    lifecycle VARCHAR(30) NOT NULL,

    -- 주문 수량이다. 원장 수량이 아니다.
    ordered_quantity NUMERIC(19, 6) NOT NULL,
    -- 원장에 쓰일 수량은 이 값이다.
    filled_quantity NUMERIC(19, 6) NOT NULL,
    -- 개별 체결가가 아니라 주문 전체의 평균 체결가다.
    average_filled_price NUMERIC(19, 4),
    -- average_filled_price * filled_quantity 와의 괴리를 검증하기 위해 함께 보존한다.
    filled_amount NUMERIC(19, 4),
    commission NUMERIC(19, 4),
    -- 세금은 보존만 하고 취득원가 계산에 넣지 않는다. 합산하면 원가의 의미가 조용히 바뀐다.
    tax NUMERIC(19, 4),
    currency_code VARCHAR(3) NOT NULL,

    ordered_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    -- 최종 체결 시각이다. 값이 없을 때 결제일로 대신 채우지 않는다.
    filled_at TIMESTAMP(6) WITH TIME ZONE,
    settlement_date DATE,

    staging_status VARCHAR(40) NOT NULL,
    skip_reason_code VARCHAR(40),

    -- 실행 단위 신호 건수만 남기면 "괴리 1건"이 어느 주문인지 알 수 없다.
    -- 어느 행인지 짚어 주지 못하는 경고는 사용자가 할 수 있는 일이 없다.
    amount_mismatch BOOLEAN NOT NULL,
    fee_unknown BOOLEAN NOT NULL,
    buy_tax BOOLEAN NOT NULL,

    CONSTRAINT fk_broker_order_import_items_run
        FOREIGN KEY (run_id) REFERENCES broker_order_import_runs (id) ON DELETE CASCADE,
    -- 커서 순회가 같은 주문을 두 번 담는 일을 DB 수준에서 막는다.
    CONSTRAINT uk_broker_order_import_items_run_order UNIQUE (run_id, external_order_id)
);

CREATE INDEX idx_broker_order_import_items_run_filled_at
    ON broker_order_import_items (run_id, filled_at);

-- 주문 식별자 불안정 감지는 계좌 단위로 지문을 비교한다.
CREATE INDEX idx_broker_order_import_items_fingerprint
    ON broker_order_import_items (content_fingerprint);

-- 실행 시점에 계산한 대조 결과다. 재구성 보유 수량과 증권사 스냅샷 수량의 종목별 차이를 남긴다.
-- 원장은 이후에도 계속 바뀌므로, 실행 결과를 나중에 다시 계산하면 그때의 답이 나온다.
-- 실행 감사는 그 시점의 답을 보존해야 하므로 값을 저장한다.
CREATE TABLE broker_order_import_reconciliation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    -- 기존 원장 + 스테이징 대상을 메모리에서 재생해 얻은 수량이다. 원장에 쓰지 않는다.
    reconstructed_quantity NUMERIC(19, 6) NOT NULL,
    -- 최신 증권사 보유 종목 스냅샷의 수량이다.
    snapshot_quantity NUMERIC(19, 6) NOT NULL,
    quantity_difference NUMERIC(19, 6) NOT NULL,

    CONSTRAINT fk_broker_order_import_reconciliation_lines_run
        FOREIGN KEY (run_id) REFERENCES broker_order_import_runs (id) ON DELETE CASCADE,
    CONSTRAINT uk_broker_order_import_reconciliation_lines_asset
        UNIQUE (run_id, market, ticker)
);

-- 원장 반영 사실을 기록하는 단일 지점이다. 이 단계(P2)에서는 어떤 코드도 이 표에 쓰지 않고
-- 읽기만 한다. 중복 반영 방지는 애플리케이션 로직이 아니라 이 표의 제약이 담당한다.
--
-- 항목 행을 나중에 보존 기간에 따라 정리하더라도 이 표는 남는다. 링크만 있어도
-- 같은 주문이 원장에 두 번 들어가는 일은 계속 막힌다.
CREATE TABLE broker_order_ledger_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broker_account_id BIGINT NOT NULL,
    external_order_id VARCHAR(255) NOT NULL,
    run_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,

    -- 취소로 trade_transactions 행이 삭제된 뒤에도 반영 당시 거래 ID를 감사 목적으로
    -- 보존해야 하므로 의도적으로 외래키 제약을 걸지 않는다(개시 잔고 승인 이력과 같은 선례).
    trade_transaction_id BIGINT,

    -- 승인 시점 값을 동결한다. 이후 증권사가 값을 정정해도 무엇을 근거로 반영했는지 남는다.
    approved_quantity NUMERIC(19, 6) NOT NULL,
    approved_price NUMERIC(19, 4) NOT NULL,
    approved_fee NUMERIC(19, 4) NOT NULL,
    approved_traded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    approved_by_member_id BIGINT NOT NULL,
    approved_at TIMESTAMP(6) NOT NULL,
    revoked_at TIMESTAMP(6),
    status VARCHAR(20) NOT NULL,

    CONSTRAINT fk_broker_order_ledger_links_account
        FOREIGN KEY (broker_account_id) REFERENCES broker_accounts (id),
    CONSTRAINT fk_broker_order_ledger_links_run
        FOREIGN KEY (run_id) REFERENCES broker_order_import_runs (id),
    CONSTRAINT fk_broker_order_ledger_links_item
        FOREIGN KEY (item_id) REFERENCES broker_order_import_items (id),
    CONSTRAINT fk_broker_order_ledger_links_approved_by_member
        FOREIGN KEY (approved_by_member_id) REFERENCES members (id)
);

-- 부분 유니크 인덱스라 취소 후 재승인은 가능하면서 동시 반영은 막힌다.
CREATE UNIQUE INDEX uk_broker_order_ledger_links_active_order
    ON broker_order_ledger_links (broker_account_id, external_order_id)
    WHERE status = 'ACTIVE';

-- 이미 반영된 주문 판정은 계좌별 활성 링크를 읽는다.
CREATE INDEX idx_broker_order_ledger_links_account_status
    ON broker_order_ledger_links (broker_account_id, status);
