-- 증권사 자격 증명을 "고정 두 열"에서 "제공자 명세가 정하는 키/값 행"으로 일반화한다.
-- 두 번째 증권사가 세 번째 입력 항목을 요구해도 이 스키마는 그대로다.
--
-- field_key 에는 외래키를 걸 수 없다. 진실의 원천은 BrokerProvider enum의 자격 증명 명세이지
-- 표가 아니다. 대신 애플리케이션이 저장 전에 명세와 대조해 화이트리스트 밖의 키를 거부한다.
--
-- encryption_key_version 은 연결 단위가 아니라 값 단위로 둔다. 한 연결 안에서 항목마다 키
-- 버전이 다를 수 있어야 무중단 키 로테이션이 가능하다.
CREATE TABLE broker_connection_secret_values (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broker_connection_id BIGINT NOT NULL,
    field_key VARCHAR(64) NOT NULL,
    ciphertext VARCHAR(4096) NOT NULL,
    initialization_vector VARCHAR(255) NOT NULL,
    encryption_key_version INTEGER NOT NULL,
    CONSTRAINT fk_broker_connection_secret_values_connection
        FOREIGN KEY (broker_connection_id) REFERENCES broker_connections (id) ON DELETE CASCADE,
    CONSTRAINT uk_broker_connection_secret_values_field
        UNIQUE (broker_connection_id, field_key)
);

-- 기존 두 열을 그대로 옮긴다. 암호문을 다시 만들지 않으므로 암호화 키가 없는 환경에서도
-- 이 마이그레이션이 실행된다. 재암호화를 여기서 하면 키가 없는 기동이 통째로 막힌다.
-- 키 이름은 BrokerProvider.TOSS_SECURITIES 의 BrokerCredentialField.key 와 같은 값이다.
INSERT INTO broker_connection_secret_values
    (broker_connection_id, field_key, ciphertext, initialization_vector, encryption_key_version)
SELECT broker_connection_id,
       'clientId',
       encrypted_client_id,
       client_id_initialization_vector,
       encryption_key_version
FROM broker_connection_secrets;

INSERT INTO broker_connection_secret_values
    (broker_connection_id, field_key, ciphertext, initialization_vector, encryption_key_version)
SELECT broker_connection_id,
       'clientSecret',
       encrypted_client_secret,
       client_secret_initialization_vector,
       encryption_key_version
FROM broker_connection_secrets;

-- broker_connection_secrets 는 여기서 지우지 않는다. 이 릴리스에서 문제가 드러나면
-- 되돌릴 수 있어야 하기 때문이다. 다만 애플리케이션 코드는 이 마이그레이션 이후 새 표만
-- 읽고 쓴다. 두 곳에 동시에 쓰면 어느 쪽이 진실인지 알 수 없게 된다.
-- 다음 릴리스의 V18 에서 드롭한다.
