-- 사용자 주도 원장 정합성 점검(S5) 스키마다.
--
-- 이 마이그레이션은 기존 테이블을 한 컬럼도 바꾸지 않는다. 점검은 저장된 최신 보유 종목
-- 스냅샷과 현재 매매 원장만 비교하며, 증권사를 호출하지 않고 trade_transactions와 holdings
-- 어느 쪽도 쓰지 않는다.
--
-- snapshot_id 에는 외래키를 걸지 않는다. 증권사 연결이 삭제되면 그 연결에서 파생된 스냅샷도
-- 함께 지워지는데(BrokerConnectionService.deleteBrokerConnection), 이 실행 기록은 그 뒤에도
-- "그때 무엇을 비교했는지"를 감사 목적으로 남겨야 한다. 필요한 사실(동기화 시각)은
-- snapshot_synced_at 컬럼에, 종목별 값은 아래 줄 테이블에 이미 그대로 복사해 둔다.
CREATE TABLE broker_reconciliation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    broker_connection_id BIGINT NOT NULL,
    broker_account_id BIGINT NOT NULL,

    snapshot_id BIGINT NOT NULL,
    snapshot_synced_at TIMESTAMP(6) NOT NULL,

    executed_by_member_id BIGINT NOT NULL,
    executed_at TIMESTAMP(6) NOT NULL,

    overall_status VARCHAR(20) NOT NULL,
    matched_count INTEGER NOT NULL,
    quantity_mismatch_count INTEGER NOT NULL,
    only_in_broker_count INTEGER NOT NULL,
    only_in_trade_guide_count INTEGER NOT NULL,

    CONSTRAINT fk_broker_reconciliation_runs_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    CONSTRAINT fk_broker_reconciliation_runs_connection
        FOREIGN KEY (broker_connection_id) REFERENCES broker_connections (id),
    CONSTRAINT fk_broker_reconciliation_runs_account
        FOREIGN KEY (broker_account_id) REFERENCES broker_accounts (id),
    CONSTRAINT fk_broker_reconciliation_runs_member
        FOREIGN KEY (executed_by_member_id) REFERENCES members (id)
);

-- 목록은 포트폴리오별 최신순 페이징이다. id를 동점 기준으로 함께 둔 이유는
-- broker_order_import_runs와 같다: 같은 executed_at을 가진 실행이 페이지 경계에서
-- 흔들리지 않아야 한다.
CREATE INDEX idx_broker_reconciliation_runs_portfolio_paging
    ON broker_reconciliation_runs (portfolio_id, executed_at DESC, id DESC);

-- 실행 한 건에 속한 종목별 비교 결과다. 보유 종목 수에 비례해 상한이 있으므로 별도로
-- 페이징하지 않고 상세 응답에 그대로 담는다.
CREATE TABLE broker_reconciliation_lines (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    market VARCHAR(10) NOT NULL,
    ticker VARCHAR(50) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    broker_quantity NUMERIC(19, 6),
    trade_guide_quantity NUMERIC(19, 6),
    comparison VARCHAR(30) NOT NULL,

    CONSTRAINT fk_broker_reconciliation_lines_run
        FOREIGN KEY (run_id) REFERENCES broker_reconciliation_runs (id) ON DELETE CASCADE
);

CREATE INDEX idx_broker_reconciliation_lines_run
    ON broker_reconciliation_lines (run_id);

-- 줄 한 건에 여러 차이 사유 후보가 함께 붙을 수 있어 컬럼이 아니라 별도 행으로 둔다.
CREATE TABLE broker_reconciliation_line_reasons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    line_id BIGINT NOT NULL,
    reason_code VARCHAR(40) NOT NULL,

    CONSTRAINT fk_broker_reconciliation_line_reasons_line
        FOREIGN KEY (line_id) REFERENCES broker_reconciliation_lines (id) ON DELETE CASCADE,
    CONSTRAINT uk_broker_reconciliation_line_reasons_unique
        UNIQUE (line_id, reason_code)
);
