-- 증권사 자격 증명 암호화 키 로테이션 실행 기록이다
-- (docs/agent-tasks/broker-credential-encryption-key-rotation.md §10).
--
-- 이 표는 실행 감사 기록일 뿐이며 ciphertext·평문·키 값을 담지 않는다. 그대로 인시던트
-- 문서에 인용해도 안전하다. 재암호화 대상 표(broker_connection_secret_values,
-- broker_accounts)는 이미 값/계좌 단위 encryption_key_version을 갖고 있으므로(V17, V8)
-- 이 마이그레이션은 두 표의 컬럼을 바꾸지 않는다.
CREATE TABLE broker_key_rotation_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    target_key_version INTEGER NOT NULL,
    -- 로테이션 시작 시점에 관측된, 목표 버전이 아닌 구버전 목록이다(쉼표로 구분한 정수 문자열).
    -- 값 자체는 담지 않으므로 그대로 감사 기록에 남겨도 안전하다.
    source_key_versions_observed VARCHAR(100),

    status VARCHAR(20) NOT NULL,

    secret_values_total INTEGER NOT NULL,
    secret_values_processed INTEGER NOT NULL DEFAULT 0,
    secret_values_skipped INTEGER NOT NULL DEFAULT 0,
    secret_values_failed INTEGER NOT NULL DEFAULT 0,

    accounts_total INTEGER NOT NULL,
    accounts_processed INTEGER NOT NULL DEFAULT 0,
    accounts_skipped INTEGER NOT NULL DEFAULT 0,
    accounts_failed INTEGER NOT NULL DEFAULT 0,

    -- 회원 행을 참조하지 않는다. 로테이션은 회원 행위가 아니라 운영 행위다
    -- (docs/agent-tasks/broker-credential-encryption-key-rotation.md §8).
    triggered_by VARCHAR(100) NOT NULL,

    started_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),

    -- 원인 예외 메시지가 아니라 고정된 사유 코드 문자열만 담는다.
    failure_reason VARCHAR(255)
);

-- 동시에 두 실행이 진행 중일 수 없다는 규칙을 DB가 강제한다. 인메모리 가드가 아니라 이
-- 부분 유니크 인덱스가 다중 인스턴스 배포에서도 유일한 진실이다
-- (docs/agent-tasks/broker-credential-encryption-key-rotation.md §6.3).
CREATE UNIQUE INDEX uk_broker_key_rotation_runs_single_in_progress
    ON broker_key_rotation_runs (status)
    WHERE status = 'IN_PROGRESS';
