CREATE TABLE members (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    nickname VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_members_email UNIQUE (email),
    CONSTRAINT uk_members_nickname UNIQUE (nickname)
);

CREATE TABLE portfolios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    name VARCHAR(255),
    created_at TIMESTAMP(6),
    max_loss_per_trade_ratio NUMERIC(8, 6),
    max_single_asset_exposure_ratio NUMERIC(8, 6),
    CONSTRAINT fk_portfolios_member
        FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE INDEX idx_portfolios_member_id ON portfolios (member_id);

CREATE TABLE trade_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    trade_type VARCHAR(255) NOT NULL,
    quantity NUMERIC(19, 6) NOT NULL,
    executed_price NUMERIC(19, 4) NOT NULL,
    fee NUMERIC(19, 4) NOT NULL,
    traded_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    CONSTRAINT fk_trade_transactions_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id)
);

CREATE INDEX idx_trade_transactions_portfolio_traded_at
    ON trade_transactions (portfolio_id, traded_at);

CREATE TABLE asset_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    investment_track VARCHAR(255) NOT NULL,
    CONSTRAINT uk_asset_profiles_market_ticker UNIQUE (market, ticker)
);

CREATE INDEX idx_asset_profiles_investment_track
    ON asset_profiles (investment_track);
