CREATE TABLE portfolio_broker_holding_adjustments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    -- 증권사 연결이 삭제되면 파생 스냅샷 항목도 함께 사라진다. 이미 취소(REVOKED)된
    -- 승인 이력은 감사 목적으로 보존해야 하므로 이 참조는 처음부터 NULL을 허용하고,
    -- 취소된 이력에 한해 참조만 끊는다. 승인 당시 값은 아래 컬럼에 이미 복사되어 있다.
    snapshot_item_id BIGINT,
    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    delta_quantity NUMERIC(19, 6) NOT NULL,
    unit_price NUMERIC(19, 4) NOT NULL,
    broker_quantity NUMERIC(19, 6) NOT NULL,
    broker_average_purchase_price NUMERIC(19, 4) NOT NULL,
    ledger_quantity_before NUMERIC(19, 6) NOT NULL,
    ledger_average_purchase_price_before NUMERIC(19, 4) NOT NULL,
    snapshot_synced_at TIMESTAMP(6) NOT NULL,
    -- 취소로 trade_transactions 행이 삭제된 뒤에도 생성 당시 거래 ID를 감사 목적으로
    -- 보존해야 하므로 의도적으로 외래키 제약을 걸지 않는다.
    trade_transaction_id BIGINT NOT NULL,
    approved_by_member_id BIGINT NOT NULL,
    approved_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_broker_holding_adjustments_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    CONSTRAINT fk_broker_holding_adjustments_snapshot_item
        FOREIGN KEY (snapshot_item_id) REFERENCES broker_holding_snapshot_items (id),
    CONSTRAINT fk_broker_holding_adjustments_approved_by_member
        FOREIGN KEY (approved_by_member_id) REFERENCES members (id),
    -- 동일 스냅샷 항목의 중복 승인을 DB 수준에서 막는다. 재승인은 새 거래를 만들지 않고
    -- 기존 결과를 돌려준다(애플리케이션 계층의 멱등 처리와 이 제약이 함께 이 규칙을 지킨다).
    CONSTRAINT uk_broker_holding_adjustments_snapshot_item UNIQUE (snapshot_item_id)
);

-- 감사 이력 조회는 포트폴리오별로 승인 시각 내림차순으로 읽는다.
CREATE INDEX idx_broker_holding_adjustments_portfolio_approved_at
    ON portfolio_broker_holding_adjustments (portfolio_id, approved_at DESC);
