CREATE TABLE portfolio_candidate_assets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    investment_track VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_portfolio_candidate_assets_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    -- 포트폴리오당 같은 종목은 후보로 한 번만 등록할 수 있다.
    CONSTRAINT uk_portfolio_candidate_assets_portfolio_market_ticker
        UNIQUE (portfolio_id, market, ticker)
);

-- 후보 가이드 생성이 포트폴리오 기준으로 후보 목록을 조회하는 경로를 뒷받침한다.
CREATE INDEX idx_portfolio_candidate_assets_portfolio
    ON portfolio_candidate_assets (portfolio_id);
