-- 주문 이력 스테이징 항목 중 사람 판단이 필요한 의심 항목(MANUAL_OVERLAP_SUSPECTED,
-- DUPLICATE_SUSPECTED)에 대한 사용자 재판정 감사 기록이다.
--
-- broker_order_import_items는 한 컬럼도 바꾸지 않는다. 항목은 "증권사가 이렇게 보고했고 우리는
-- 이렇게 읽었다"는 사실이고, 사용자의 판단은 이 표에 따로 남긴다. 승인 경로는 두 값을 합쳐
-- 유효 상태를 계산하며, 유효 상태가 STAGED인 항목만 반영 후보다.
CREATE TABLE broker_order_import_item_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id BIGINT NOT NULL,
    item_id BIGINT NOT NULL,
    external_order_id VARCHAR(255) NOT NULL,
    original_staging_status VARCHAR(40) NOT NULL,
    original_skip_reason_code VARCHAR(40),
    decision VARCHAR(30) NOT NULL,
    -- 새 상태를 만들지 않는다. 기존 스테이징 상태 값 가운데 하나이며 의미도 같다.
    resulting_staging_status VARCHAR(40) NOT NULL,
    reason VARCHAR(500) NOT NULL,
    created_by_member_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,

    -- 감사 기록이므로 실행·항목 삭제에 연쇄되지 않는다(원장 링크와 같은 선례).
    CONSTRAINT fk_broker_order_import_item_overrides_run
        FOREIGN KEY (run_id) REFERENCES broker_order_import_runs (id),
    CONSTRAINT fk_broker_order_import_item_overrides_item
        FOREIGN KEY (item_id) REFERENCES broker_order_import_items (id),
    CONSTRAINT fk_broker_order_import_item_overrides_created_by
        FOREIGN KEY (created_by_member_id) REFERENCES members (id),
    -- 항목 하나에 재판정은 한 번뿐이다. 동시 요청의 중복 기록을 애플리케이션이 아니라 DB가 막는다.
    CONSTRAINT uk_broker_order_import_item_overrides_item UNIQUE (item_id),
    CONSTRAINT ck_broker_order_import_item_overrides_original_status
        CHECK (original_staging_status IN ('MANUAL_OVERLAP_SUSPECTED', 'DUPLICATE_SUSPECTED')),
    CONSTRAINT ck_broker_order_import_item_overrides_decision_result
        CHECK ((decision = 'ALLOW_LEDGER_WRITE' AND resulting_staging_status = 'STAGED')
            OR (decision = 'KEEP_EXCLUDED' AND resulting_staging_status = original_staging_status)),
    CONSTRAINT ck_broker_order_import_item_overrides_reason
        CHECK (LENGTH(TRIM(reason)) > 0)
);

-- 감사 이력 조회는 실행별 최신순으로 읽는다.
CREATE INDEX idx_broker_order_import_item_overrides_run_created_at
    ON broker_order_import_item_overrides (run_id, created_at DESC, id DESC);

-- 원장 링크가 어떤 재판정을 근거로 쓰였는지 남긴다. 분류기가 처음부터 STAGED로 본 주문은 비어 있다.
ALTER TABLE broker_order_ledger_links
    ADD COLUMN override_id BIGINT;

ALTER TABLE broker_order_ledger_links
    ADD CONSTRAINT fk_broker_order_ledger_links_override
        FOREIGN KEY (override_id) REFERENCES broker_order_import_item_overrides (id);
