CREATE TABLE premarket_guide_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    guide_date DATE NOT NULL,
    generated_at TIMESTAMP(6) NOT NULL,
    status VARCHAR(20) NOT NULL,
    held_guide_count INTEGER NOT NULL,
    candidate_guide_count INTEGER NOT NULL,
    unavailable_count INTEGER NOT NULL,
    held_empty_reason VARCHAR(50),
    held_empty_message VARCHAR(1000),
    CONSTRAINT fk_premarket_guide_snapshots_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    CONSTRAINT uk_premarket_guide_snapshots_portfolio_date
        UNIQUE (portfolio_id, guide_date)
);

CREATE INDEX idx_premarket_guide_snapshots_portfolio_date
    ON premarket_guide_snapshots (portfolio_id, guide_date);

CREATE TABLE premarket_guide_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL,
    scope VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    market VARCHAR(20) NOT NULL,
    ticker VARCHAR(100) NOT NULL,
    action VARCHAR(20),
    reason VARCHAR(2000),
    reference_price NUMERIC(19, 6),
    data_as_of DATE,
    strategy_id VARCHAR(100),
    strategy_version VARCHAR(50),
    confidence VARCHAR(50),
    caveats TEXT,
    trend VARCHAR(30),
    signal_event VARCHAR(30),
    weeks_since_cross INTEGER,
    entry_timing_status VARCHAR(50),
    entry_timing_message VARCHAR(2000),
    stop_loss_status VARCHAR(50),
    stop_loss_ratio NUMERIC(8, 6),
    stop_loss_price NUMERIC(19, 6),
    stop_loss_message VARCHAR(2000),
    unavailable_reason VARCHAR(50),
    CONSTRAINT fk_premarket_guide_items_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES premarket_guide_snapshots (id)
);

CREATE INDEX idx_premarket_guide_items_snapshot_scope
    ON premarket_guide_items (snapshot_id, scope, market, ticker);
