CREATE TABLE portfolio_asset_risk_overrides (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    stop_loss_ratio NUMERIC(8, 6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_portfolio_asset_risk_overrides_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    -- 포트폴리오당 종목 하나에는 손절 기준 재정의를 하나만 허용한다.
    CONSTRAINT uk_portfolio_asset_risk_overrides_portfolio_market_ticker
        UNIQUE (portfolio_id, market, ticker)
);

-- 보유 종목 가이드 생성이 포트폴리오+종목으로 재정의를 조회하는 경로를 뒷받침한다.
CREATE INDEX idx_portfolio_asset_risk_overrides_portfolio
    ON portfolio_asset_risk_overrides (portfolio_id);
