CREATE TABLE broker_order_execution_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    broker_connection_id BIGINT NOT NULL,
    strategy_id VARCHAR(100) NOT NULL,
    max_position_size_per_order_percent NUMERIC(5, 4) NOT NULL,
    max_daily_order_count INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    consented_at TIMESTAMP(6) NOT NULL,
    consent_version VARCHAR(50) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_broker_order_execution_grants_member
        FOREIGN KEY (member_id) REFERENCES members (id),
    CONSTRAINT fk_broker_order_execution_grants_connection
        FOREIGN KEY (broker_connection_id) REFERENCES broker_connections (id),
    -- 증권사 연결 한 건당 동의는 하나뿐이다. 생애주기(ACTIVE/PAUSED/REVOKED)는 이
    -- 한 행의 상태 전이로 관리하고, 재동의는 새 연결을 만들지 않는 한 새 행을
    -- 만들지 않는다 - 철회 이력을 잃지 않으면서 "이 연결의 동의 상태"를 항상
    -- 한 곳에서만 조회할 수 있게 한다.
    CONSTRAINT uk_broker_order_execution_grants_connection
        UNIQUE (broker_connection_id)
);

CREATE INDEX idx_broker_order_execution_grants_member
    ON broker_order_execution_grants (member_id);

CREATE TABLE broker_order_execution_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    grant_id BIGINT NOT NULL,
    strategy_id VARCHAR(100) NOT NULL,
    ticker VARCHAR(20) NOT NULL,
    side VARCHAR(10) NOT NULL,
    requested_quantity NUMERIC(19, 6) NOT NULL,
    status VARCHAR(30) NOT NULL,
    started_at TIMESTAMP(6) NOT NULL,
    completed_at TIMESTAMP(6),
    failure_reason_code VARCHAR(100),
    CONSTRAINT fk_broker_order_execution_runs_grant
        FOREIGN KEY (grant_id) REFERENCES broker_order_execution_grants (id)
);

-- 동의 하나에 대한 실행 이력을 최신순으로 조회하는 것이 감사 화면의 기본 조회 패턴이다.
CREATE INDEX idx_broker_order_execution_runs_grant_started_at
    ON broker_order_execution_runs (grant_id, started_at DESC);
