CREATE TABLE premarket_guide_candle_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL,
    scope VARCHAR(20) NOT NULL,
    market VARCHAR(20) NOT NULL,
    ticker VARCHAR(100) NOT NULL,
    candle_provider VARCHAR(50) NOT NULL,
    load_completed_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    candle_sha256 VARCHAR(64) NOT NULL,
    candle_count INTEGER NOT NULL,
    data_as_of DATE NOT NULL,
    CONSTRAINT fk_premarket_guide_candle_evidence_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES premarket_guide_snapshots (id),
    CONSTRAINT uk_premarket_guide_candle_evidence_asset
        UNIQUE (snapshot_id, scope, market, ticker)
);
