CREATE TABLE asset_listings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    listing_status VARCHAR(255) NOT NULL,
    CONSTRAINT uk_asset_listings_market_ticker UNIQUE (market, ticker)
);

INSERT INTO asset_listings (market, ticker, display_name, listing_status)
SELECT market, ticker, ticker, 'ACTIVE'
FROM asset_profiles;

ALTER TABLE asset_profiles ADD COLUMN listing_id BIGINT;

UPDATE asset_profiles profile
SET listing_id = listing.id
FROM asset_listings listing
WHERE profile.market = listing.market
  AND profile.ticker = listing.ticker;

ALTER TABLE asset_profiles ALTER COLUMN listing_id SET NOT NULL;
ALTER TABLE asset_profiles
    ADD CONSTRAINT fk_asset_profiles_listing
    FOREIGN KEY (listing_id) REFERENCES asset_listings (id);
ALTER TABLE asset_profiles
    ADD CONSTRAINT uk_asset_profiles_listing UNIQUE (listing_id);
ALTER TABLE asset_profiles DROP CONSTRAINT uk_asset_profiles_market_ticker;
ALTER TABLE asset_profiles DROP COLUMN market;
ALTER TABLE asset_profiles DROP COLUMN ticker;
