CREATE TABLE broker_connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    member_id BIGINT NOT NULL,
    provider VARCHAR(50) NOT NULL,
    display_name VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL,
    masked_account_label VARCHAR(255),
    last_verified_at TIMESTAMP(6),
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_broker_connections_member
        FOREIGN KEY (member_id) REFERENCES members (id)
);

CREATE INDEX idx_broker_connections_member_created_at
    ON broker_connections (member_id, created_at DESC);

CREATE TABLE broker_connection_secrets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broker_connection_id BIGINT NOT NULL,
    encrypted_client_id VARCHAR(4096) NOT NULL,
    client_id_initialization_vector VARCHAR(255) NOT NULL,
    encrypted_client_secret VARCHAR(4096) NOT NULL,
    client_secret_initialization_vector VARCHAR(255) NOT NULL,
    encryption_key_version INTEGER NOT NULL,
    CONSTRAINT uk_broker_connection_secrets_connection UNIQUE (broker_connection_id),
    CONSTRAINT fk_broker_connection_secrets_connection
        FOREIGN KEY (broker_connection_id) REFERENCES broker_connections (id)
);
