CREATE TABLE broker_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    broker_connection_id BIGINT NOT NULL,
    encrypted_account_sequence VARCHAR(1024) NOT NULL,
    account_sequence_initialization_vector VARCHAR(255) NOT NULL,
    masked_account_number VARCHAR(255) NOT NULL,
    account_type VARCHAR(50) NOT NULL,
    CONSTRAINT fk_broker_accounts_connection
        FOREIGN KEY (broker_connection_id) REFERENCES broker_connections (id)
);

CREATE INDEX idx_broker_accounts_connection ON broker_accounts (broker_connection_id);
