ALTER TABLE broker_accounts
    ADD COLUMN encryption_key_version INTEGER NOT NULL DEFAULT 1;

CREATE TABLE portfolio_broker_links (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    broker_connection_id BIGINT NOT NULL,
    broker_account_id BIGINT NOT NULL,
    linked_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_portfolio_broker_links_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    CONSTRAINT fk_portfolio_broker_links_connection
        FOREIGN KEY (broker_connection_id) REFERENCES broker_connections (id),
    CONSTRAINT fk_portfolio_broker_links_account
        FOREIGN KEY (broker_account_id) REFERENCES broker_accounts (id)
);

-- 포트폴리오당 하나의 활성 링크 제약은 v1 서비스 검증 사항이므로 스키마에 고정하지 않는다.
CREATE INDEX idx_portfolio_broker_links_portfolio
    ON portfolio_broker_links (portfolio_id);

CREATE INDEX idx_portfolio_broker_links_connection
    ON portfolio_broker_links (broker_connection_id);
