CREATE TABLE broker_holding_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    portfolio_id BIGINT NOT NULL,
    broker_connection_id BIGINT NOT NULL,
    broker_account_id BIGINT NOT NULL,
    synced_at TIMESTAMP(6) NOT NULL,
    unsupported_market_count INTEGER NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_broker_holding_snapshots_portfolio
        FOREIGN KEY (portfolio_id) REFERENCES portfolios (id),
    CONSTRAINT fk_broker_holding_snapshots_connection
        FOREIGN KEY (broker_connection_id) REFERENCES broker_connections (id),
    CONSTRAINT fk_broker_holding_snapshots_account
        FOREIGN KEY (broker_account_id) REFERENCES broker_accounts (id)
);

-- 최근 스냅샷 조회는 포트폴리오별로 synced_at 내림차순 한 건만 읽는다.
CREATE INDEX idx_broker_holding_snapshots_portfolio_synced_at
    ON broker_holding_snapshots (portfolio_id, synced_at DESC);

CREATE TABLE broker_holding_snapshot_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    snapshot_id BIGINT NOT NULL,
    market VARCHAR(255) NOT NULL,
    ticker VARCHAR(255) NOT NULL,
    display_name VARCHAR(255) NOT NULL,
    quantity NUMERIC(19, 6) NOT NULL,
    average_purchase_price NUMERIC(19, 4) NOT NULL,
    CONSTRAINT fk_broker_holding_snapshot_items_snapshot
        FOREIGN KEY (snapshot_id) REFERENCES broker_holding_snapshots (id) ON DELETE CASCADE
);

CREATE INDEX idx_broker_holding_snapshot_items_snapshot
    ON broker_holding_snapshot_items (snapshot_id);
